#!/bin/bash

[ -e ./ssl ] || mkdir ./ssl

[ -z $PUBLIC_ADDRESS ] && PUBLIC_ADDRESS="kbase.us"
export PUBLIC_ADDRESS

# Create certs for development deploy
if [ -e ./ssl/proxy.key ] ; then
  echo "Skipping proxy cert"
else
  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ./ssl/proxy.key -out ./ssl/proxy.crt -config openssl.cnf  -batch
fi
  
if [ -e ./ssl/narrative.key ] ; then
  echo "Skipping narrative cert"
else
  cp ./ssl/proxy.key ./ssl/narrative.key
  cp ./ssl/proxy.crt ./ssl/narrative.crt
fi
