#!/bin/sh

if [ "z$1" = "zshell" ] ; then
    exec $DSHELL -l
elif [ "z$1" = "zsetup" ] ; then
    cat << EOF
G=\$(docker run -i -v /run/docker.sock:/run/docker.sock --entrypoint ls kbase/kb-sdk -l /run/docker.sock|awk '{print \$4}');
alias kb-sdk='docker run -it --rm -v \$HOME:\$HOME -u \$(id -u) -w \$(pwd) -v /run/docker.sock:/run/docker.sock  -e DUSER=\$USER -e DSHELL=\$SHELL --group-add \$G kbase/kb-sdk'
EOF
elif [ "z$1" = "zsdkbase" ] ; then
    echo "Pulling the base image"
    docker pull kbase/sdkbase
    #docker rmi -f kbase/deplbase:latest
    #cd /src/sdkbase && ./makeconfig
    #docker build --no-cache -t kbase/kbase:sdkbase.latest sdkbase
elif [ "z$1" = "zprune" ] ; then
  echo "Used during build to shrink image.  Not needed by the user."
  for f in $(find /src/submodules/jars/lib/jars -type f -name '*.jar') ; do
    if [ $(grep -c $f /src/bin/kb-sdk) -eq 0 ] ; then
      rm $f
    fi
  done
else
  exec kb-sdk $@
fi
