/* Generated By:JavaCC: Do not edit this line. SpecParserConstants.java */
package us.kbase.jkidl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SpecParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_include = 8;
  /** RegularExpression Id. */
  int T_module = 9;
  /** RegularExpression Id. */
  int T_auth = 10;
  /** RegularExpression Id. */
  int T_required = 11;
  /** RegularExpression Id. */
  int T_optional = 12;
  /** RegularExpression Id. */
  int T_none = 13;
  /** RegularExpression Id. */
  int T_typedef = 14;
  /** RegularExpression Id. */
  int T_funcdef = 15;
  /** RegularExpression Id. */
  int T_string = 16;
  /** RegularExpression Id. */
  int T_int = 17;
  /** RegularExpression Id. */
  int T_float = 18;
  /** RegularExpression Id. */
  int T_unobj = 19;
  /** RegularExpression Id. */
  int T_list = 20;
  /** RegularExpression Id. */
  int T_mapping = 21;
  /** RegularExpression Id. */
  int T_structure = 22;
  /** RegularExpression Id. */
  int T_tuple = 23;
  /** RegularExpression Id. */
  int T_returns = 24;
  /** RegularExpression Id. */
  int T_async = 25;
  /** RegularExpression Id. */
  int T_round_open_bracket = 26;
  /** RegularExpression Id. */
  int T_round_close_bracket = 27;
  /** RegularExpression Id. */
  int T_comma = 28;
  /** RegularExpression Id. */
  int T_dot = 29;
  /** RegularExpression Id. */
  int T_semicolon = 30;
  /** RegularExpression Id. */
  int T_colon = 31;
  /** RegularExpression Id. */
  int T_figure_open_bracket = 32;
  /** RegularExpression Id. */
  int T_figure_close_bracket = 33;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 37;
  /** RegularExpression Id. */
  int INCLUDE_LITERAL = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"#include\"",
    "\"module\"",
    "\"authentication\"",
    "\"required\"",
    "\"optional\"",
    "\"none\"",
    "\"typedef\"",
    "\"funcdef\"",
    "\"string\"",
    "\"int\"",
    "\"float\"",
    "\"UnspecifiedObject\"",
    "\"list\"",
    "\"mapping\"",
    "\"structure\"",
    "\"tuple\"",
    "\"returns\"",
    "\"async\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL_CHARS>",
    "<INCLUDE_LITERAL>",
    "\"<\"",
    "\">\"",
  };

}
