
package us.kbase.narrativemethodstore;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: AutoGeneratedValue</p>
 * <pre>
 * prefix - optional string concatenated before generated part
 * symbols - number of generated characters, optional, default is 8
 * suffix - optional string concatenated after generated part
 * @optional prefix symbols suffix
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "prefix",
    "symbols",
    "suffix"
})
public class AutoGeneratedValue {

    @JsonProperty("prefix")
    private String prefix;
    @JsonProperty("symbols")
    private Long symbols;
    @JsonProperty("suffix")
    private String suffix;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("prefix")
    public String getPrefix() {
        return prefix;
    }

    @JsonProperty("prefix")
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    public AutoGeneratedValue withPrefix(String prefix) {
        this.prefix = prefix;
        return this;
    }

    @JsonProperty("symbols")
    public Long getSymbols() {
        return symbols;
    }

    @JsonProperty("symbols")
    public void setSymbols(Long symbols) {
        this.symbols = symbols;
    }

    public AutoGeneratedValue withSymbols(Long symbols) {
        this.symbols = symbols;
        return this;
    }

    @JsonProperty("suffix")
    public String getSuffix() {
        return suffix;
    }

    @JsonProperty("suffix")
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    public AutoGeneratedValue withSuffix(String suffix) {
        this.suffix = suffix;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((("AutoGeneratedValue"+" [prefix=")+ prefix)+", symbols=")+ symbols)+", suffix=")+ suffix)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
